[options]
admin_passwd = Root@123
db_host = 127.0.0.1
db_port = 5432
db_user = Root
db_password = Root@123
db_name = ShopifyOdooConnector
addons_path = /var/www/html/shopifyConnector/ShopifyOdooConnector/odoo/odoo/addons,/var/www/html/shopifyConnector/ShopifyOdooConnector/odoo/addons,/var/www/html/shopifyConnector/ShopifyOdooConnector/custom/addons
data_dir = /var/www/html/shopifyConnector/ShopifyOdooConnector/data
logfile = /var/www/html/shopifyConnector/ShopifyOdooConnector/log/odoo.log
http_port = 8069
http_interface = 0.0.0.0
